package com.example.lab456.repositories.normal;

import com.example.lab456.entities.CurrencyEntity;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

public interface CurrencyRepository extends CrudRepository<CurrencyEntity, Long> {
    //auto-generated by framework
    CurrencyEntity findByName(String name);

    //query example 4

    @Query(value = "select * from currencies", nativeQuery = true)
    List<CurrencyEntity> findAll();
}
